name: cd

on:
    push:
        branches: [main]

jobs:
    deploy:
        name: deploy
        runs-on: ubuntu-latest

        steps:
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.20"

            - name: Check out code
              uses: actions/checkout@v3

            - name: Build app
              run: ./scripts/buildprod.sh

            - id: "auth"
              uses: "google-github-actions/auth@v1"
              with:
                  credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

            - name: "Set up Cloud SDK"
              uses: "google-github-actions/setup-gcloud@v1"

            - name: "Build docker img and push to artifact registry"
              run: gcloud builds submit --tag asia-southeast1-docker.pkg.dev/notely-398904/notely/zendi/notely:450f8fbcdaa3 .

            - name: "Deploy to Cloud Run"
              run: gcloud run deploy notely --image asia-southeast1-docker.pkg.dev/notely-398904/notely/zendi/notely:450f8fbcdaa3 --region us-central1 --allow-unauthenticated --project notely-398904 --max-instances=4
